name: First Workflow
on: workflow_dispatch
jobs:
  first-job:  # Custom job name
    runs-on: ubuntu-latest # Defines runner(environment)
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
